/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BDD.*;
import java.awt.BorderLayout;
import java.awt.Container;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
/*
import org.jfree.chart.ChartPanel;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.general.PieDataset;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartFactory;
*/
/**
 *
 * @author Axel
 */
public class GUI_reporting extends javax.swing.JFrame {

    int action;
 
    /**
     * Creates new form GUI_statistique
     */
    public GUI_reporting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReporting = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        btnLancerStat = new javax.swing.JButton();
        panelHistogramme = new javax.swing.JPanel();
        lblPopu = new javax.swing.JLabel();
        btnHistoriqueRequetes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblReporting.setBackground(new java.awt.Color(153, 153, 153));
        lblReporting.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblReporting.setText("Reporting");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choisir une population", "Nombre d'employé par tranches de salaires", "Nombre d'employé par sevice", "Nombre d'employé par spécialité", "Nombre d'employé par rotation", "Salaire des employés par service", "Salaire des employés par spécialité", "Salaire des employés par métier", "Nombre de malades par service", "Nombre de malades par mutuelle", "Nombre de chambres par service" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        btnLancerStat.setBackground(new java.awt.Color(0, 102, 0));
        btnLancerStat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLancerStat.setText("Lancer l'étude");
        btnLancerStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancerStatActionPerformed(evt);
            }
        });

        panelHistogramme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelHistogrammeLayout = new javax.swing.GroupLayout(panelHistogramme);
        panelHistogramme.setLayout(panelHistogrammeLayout);
        panelHistogrammeLayout.setHorizontalGroup(
            panelHistogrammeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        panelHistogrammeLayout.setVerticalGroup(
            panelHistogrammeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        lblPopu.setText("Population à étudier :");

        btnHistoriqueRequetes.setBackground(new java.awt.Color(0, 102, 0));
        btnHistoriqueRequetes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnHistoriqueRequetes.setText("Historique des requêtes ");
        btnHistoriqueRequetes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriqueRequetesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnHistoriqueRequetes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLancerStat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelHistogramme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(222, 222, 222))))
                    .addComponent(lblPopu, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblReporting, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(lblPopu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(btnLancerStat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHistoriqueRequetes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelHistogramme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLancerStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancerStatActionPerformed
        // TODO add your handling code here:
        
        // faire la requete sql et ranger les variables aux bon endroits
        
      
            switch(action)
            { 
                case 1 : break;
                //nombre d'employe par tranche de salaires
                default: 
                    panelHistogramme = new JPanel(new BorderLayout()); 
                        setContentPane(panelHistogramme); 
                        DefaultPieDataset pieDataset = new DefaultPieDataset();
                        pieDataset.setValue("Valeur1", new Integer(27));
                        pieDataset.setValue("Valeur2", new Integer(10));
                        pieDataset.setValue("Valeur3", new Integer(50));
                        pieDataset.setValue("Valeur4", new Integer(5));
                        JFreeChart pieChart = ChartFactory.createPieChart("Test camembert",pieDataset, true, true, true);
                        ChartPanel cPanel = new ChartPanel(pieChart);
                        this.panelHistogramme.add(cPanel);
                        this.panelHistogramme.setVisible(true);
                        break;
                       
            }
        
    
        
        
        /*
        DefaultPieDataset pieDataset = new DefaultPieDataset(); 
        pieDataset.setValue("Valeur1", new Integer(27)); 
        pieDataset.setValue("Valeur2", new Integer(10)); 
        pieDataset.setValue("Valeur3", new Integer(50)); 
        pieDataset.setValue("Valeur4", new Integer(5)); 
        JFreeChart pieChart = ChartFactory.createPieChart("Test camembert",pieDataset, true, true, true); 
        ChartPanel cPanel = new ChartPanel(pieChart); 
        panelHistogramme.add(cPanel); 
        */
        
    }//GEN-LAST:event_btnLancerStatActionPerformed

    private void btnHistoriqueRequetesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriqueRequetesActionPerformed
        // TODO add your handling code here:
        
        //ouvrir le fichier où sont rangé les requetes
        
        
    }//GEN-LAST:event_btnHistoriqueRequetesActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        
        if((jComboBox1.getSelectedIndex()!=0)||(jComboBox1.getSelectedIndex()!=-1)){
            action = jComboBox1.getSelectedIndex();
 
            
        }
                
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_reporting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_reporting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoriqueRequetes;
    private javax.swing.JButton btnLancerStat;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel lblPopu;
    private javax.swing.JLabel lblReporting;
    private javax.swing.JPanel panelHistogramme;
    // End of variables declaration//GEN-END:variables
}
