/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BDD.*;
import java.util.*;
/**
 *
 * @author Axel
 */
public class GUI_rechercher extends javax.swing.JFrame {

    /**
     * Creates new form GUI_rechercher
     */
    public GUI_rechercher() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        lblRechercher = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ckbNom = new javax.swing.JCheckBox();
        txtNom = new javax.swing.JTextField();
        rdbEmploye = new javax.swing.JRadioButton();
        rdbMalade = new javax.swing.JRadioButton();
        rdbInfirmier = new javax.swing.JRadioButton();
        rdbDocteur = new javax.swing.JRadioButton();
        ckbPrenom = new javax.swing.JCheckBox();
        txtPrenom = new javax.swing.JTextField();
        txtMutuelle = new javax.swing.JTextField();
        ckbMutuelle = new javax.swing.JCheckBox();
        ckbTel = new javax.swing.JCheckBox();
        txtTel = new javax.swing.JTextField();
        ckbAdresse = new javax.swing.JCheckBox();
        txtAdresse = new javax.swing.JTextField();
        cbRotation = new javax.swing.JComboBox();
        ckbRotation = new javax.swing.JCheckBox();
        ckbSalaire = new javax.swing.JCheckBox();
        txtValSalaire = new javax.swing.JTextField();
        cbSupInf = new javax.swing.JComboBox();
        ckbNomService = new javax.swing.JCheckBox();
        ckbHospitalisation = new javax.swing.JCheckBox();
        ckbMedecinTraitant = new javax.swing.JCheckBox();
        ckbService = new javax.swing.JCheckBox();
        txtNomService = new javax.swing.JTextField();
        ckbNomBatiment = new javax.swing.JCheckBox();
        txtNomBatiment = new javax.swing.JTextField();
        ckbDirecteur = new javax.swing.JCheckBox();
        txtNumDirecteur = new javax.swing.JTextField();
        ckbSpecialite = new javax.swing.JCheckBox();
        txtMedecinTraitant = new javax.swing.JTextField();
        ckbChambre = new javax.swing.JCheckBox();
        cbSpecialite = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaRecherche = new javax.swing.JTextArea();
        btnLancerRecherche = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRechercher.setBackground(new java.awt.Color(153, 153, 153));
        lblRechercher.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblRechercher.setText("Rechercher");

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Paramètres de recherche");

        ckbNom.setText("Nom");

        txtNom.setText("Entrer nom");
        txtNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbEmploye);
        rdbEmploye.setText("Employé");

        buttonGroup1.add(rdbMalade);
        rdbMalade.setText("Malade");

        buttonGroup1.add(rdbInfirmier);
        rdbInfirmier.setText("Infirmier");

        buttonGroup1.add(rdbDocteur);
        rdbDocteur.setText("Docteur");

        ckbPrenom.setText("Prenom");
        ckbPrenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbPrenomActionPerformed(evt);
            }
        });

        txtPrenom.setText("Entrer prenom");

        txtMutuelle.setText("nom mutuelle");

        ckbMutuelle.setText("Mutuelle");
        ckbMutuelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMutuelleActionPerformed(evt);
            }
        });

        ckbTel.setText("Tel");
        ckbTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbTelActionPerformed(evt);
            }
        });

        txtTel.setText("entrez tel");

        ckbAdresse.setText("Adresse");
        ckbAdresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbAdresseActionPerformed(evt);
            }
        });

        txtAdresse.setText("tout ou partie");

        cbRotation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jour", "Nuit" }));

        ckbRotation.setText("Rotation");
        ckbRotation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbRotationActionPerformed(evt);
            }
        });

        ckbSalaire.setText("Salaire");
        ckbSalaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSalaireActionPerformed(evt);
            }
        });

        txtValSalaire.setText("valeur (en €)");

        cbSupInf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ">", "<" }));

        ckbNomService.setText("Nom");
        ckbNomService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNomServiceActionPerformed(evt);
            }
        });

        ckbHospitalisation.setText("Hospitalisations");
        ckbHospitalisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbHospitalisationActionPerformed(evt);
            }
        });

        ckbMedecinTraitant.setText("Médecin Traitant");
        ckbMedecinTraitant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbMedecinTraitantActionPerformed(evt);
            }
        });

        ckbService.setText("Service");
        ckbService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbServiceActionPerformed(evt);
            }
        });

        txtNomService.setText("nom service");

        ckbNomBatiment.setText("Batiment");
        ckbNomBatiment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbNomBatimentActionPerformed(evt);
            }
        });

        txtNomBatiment.setText("nom batiment");

        ckbDirecteur.setText("Directeur");
        ckbDirecteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbDirecteurActionPerformed(evt);
            }
        });

        txtNumDirecteur.setText("numéro");

        ckbSpecialite.setText("Spécialité");
        ckbSpecialite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbSpecialiteActionPerformed(evt);
            }
        });

        txtMedecinTraitant.setText("nom médecin");
        txtMedecinTraitant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedecinTraitantActionPerformed(evt);
            }
        });

        ckbChambre.setText("Infos Chambre");
        ckbChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbChambreActionPerformed(evt);
            }
        });

        cbSpecialite.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Generaliste", "Anesthesiste", "Cardiologue", "Generaliste", "Orthopediste", "Pneumologue", "Radiologue", "Traumatologue" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ckbNom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbTel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckbAdresse))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdresse)
                            .addComponent(txtTel)
                            .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(txtNom)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(rdbDocteur, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rdbInfirmier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rdbMalade)
                                    .addComponent(rdbEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ckbMutuelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ckbMedecinTraitant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(ckbHospitalisation, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMutuelle, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addComponent(txtMedecinTraitant))
                                    .addComponent(ckbChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(ckbSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbSupInf, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbSpecialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(ckbDirecteur)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNumDirecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(ckbSpecialite, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(65, 65, 65))
                                                    .addComponent(ckbNomBatiment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addComponent(ckbService, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ckbNomService, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(ckbRotation, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(43, 43, 43)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNomService)
                                            .addComponent(txtNomBatiment)
                                            .addComponent(cbRotation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                        .addGap(1, 1, 1)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ckbNom)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbPrenom)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbTel)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbAdresse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMutuelle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbMutuelle)
                    .addComponent(rdbMalade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbMedecinTraitant)
                    .addComponent(txtMedecinTraitant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbHospitalisation)
                    .addComponent(ckbChambre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdbEmploye)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbInfirmier)
                    .addComponent(cbRotation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbRotation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbSalaire)
                    .addComponent(cbSupInf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValSalaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ckbNomService)
                    .addComponent(txtNomService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbService))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomBatiment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbNomBatiment))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumDirecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ckbDirecteur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbSpecialite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ckbSpecialite)
                        .addComponent(rdbDocteur)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.getAccessibleContext().setAccessibleName("Paramètres de recherche");

        txtAreaRecherche.setColumns(20);
        txtAreaRecherche.setRows(5);
        txtAreaRecherche.setText("Espace réponse\n");
        jScrollPane1.setViewportView(txtAreaRecherche);

        btnLancerRecherche.setBackground(new java.awt.Color(0, 102, 0));
        btnLancerRecherche.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLancerRecherche.setText("Lancer la recherche");
        btnLancerRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLancerRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLancerRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblRechercher, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLancerRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLancerRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLancerRechercheActionPerformed
        // TODO add your handling code here:
        
        // On crée une requête SQL à partir des cases cochées
        System.out.println("Requête recherche :");
        String Requete = new String();
        ArrayList<String> Select = new ArrayList<String>();
        ArrayList<String> From = new ArrayList<String>();
        ArrayList<String> Where = new ArrayList<String>();
        //Recuperation des conditions de la requete
        Select.add("*");
        if (ckbNom.isSelected()){
            Where.add("nom == '" + txtNom.getText() + "'");
        }
        if (ckbPrenom.isSelected()){
            Where.add("prenom == '" + txtPrenom.getText() + "'");
        }
        if (ckbTel.isSelected()){
            Where.add("tel == '" + txtTel.getText() + "'");
        }
        if (ckbAdresse.isSelected()){
            Where.add("adresse == '" + txtAdresse.getText() + "'");
        }
        
        
        if (rdbMalade.isSelected()){
            From.add("malade");
            if (ckbMutuelle.isSelected()){
                Where.add("mutuelle == '" + txtMutuelle.getText() + "'");
            }
            if (ckbMedecinTraitant.isSelected()){
                From.add("soigne");
                From.add("docteur");
                Where.add("soigne.no_malade == malade.numero");
                Where.add("soigne.no_docteur == docteur.numero");
            }
            if (ckbHospitalisation.isSelected()){
                From.add("Hospitalisation");
                Where.add("malde.numero == hospitalisation.no_malade");
                if (ckbChambre.isSelected()){
                    From.add("Chambre");
                    From.add("Service");
                    Where.add("Hospitalisation.no_chambre == Chambre.no_chambre");
                }
            }
        }
        if (rdbEmploye.isSelected()){
            From.add("Employe");
        }
        if (rdbInfirmier.isSelected()){
            From.add("Infirmier");
            if(ckbRotation.isSelected()){
                Where.add("Infirmier.rotation == '" + cbRotation.getSelectedItem().toString() + "'");
            }
            if(ckbSalaire.isSelected()){
                Where.add("Infirmier.salaire " + cbSupInf.getSelectedItem().toString() + "= " + txtValSalaire.getText());
                if(ckbService.isSelected()){
                    From.add("Service");
                    Where.add("Infirmier.code_service == service.code");
                    if(ckbNomService.isSelected()){
                        Where.add("Service.code == " + txtNomService.getText());
                    }
                    if(ckbNomBatiment.isSelected()){
                        Where.add("Service.batiment == " + txtNomBatiment.getText());
                    }
                    if(ckbDirecteur.isSelected()){
                        Where.add("Service.directeur == " + Integer.parseInt(txtNumDirecteur.getText()));
                    }
                }
            }
        }
        if (rdbDocteur.isSelected()){
            From.add("Docteur");
            if(ckbSpecialite.isSelected()){
                Where.add("Docteur.specialite == " + cbSpecialite.getSelectedItem().toString());
            }
        }
        
        
        //Somme des Select
        Requete += "select " + Select.get(0);
        for(int i=1;i<Select.size();i++){
            Requete += "," + Select.get(i);
        }
        //Somme des From
        Requete += "\nfrom " + From.get(0);
        for(int i=1;i<From.size();i++){
            Requete += "," + From.get(i);
        }
        //Somme des conditions
        Requete += "\nwhere " + Where.get(0);
        for(int i=1;i<Where.size();i++){
            Requete += "\nand " + Where.get(i);
        }
        System.out.println(Requete);
    }//GEN-LAST:event_btnLancerRechercheActionPerformed

    private void ckbPrenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbPrenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbPrenomActionPerformed

    private void txtNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomActionPerformed

    private void ckbMutuelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMutuelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbMutuelleActionPerformed

    private void ckbTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbTelActionPerformed

    private void ckbAdresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbAdresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbAdresseActionPerformed

    private void ckbRotationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbRotationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbRotationActionPerformed

    private void ckbSalaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSalaireActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbSalaireActionPerformed

    private void ckbNomServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNomServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbNomServiceActionPerformed

    private void ckbHospitalisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbHospitalisationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbHospitalisationActionPerformed

    private void ckbMedecinTraitantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbMedecinTraitantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbMedecinTraitantActionPerformed

    private void ckbServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbServiceActionPerformed

    private void ckbNomBatimentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbNomBatimentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbNomBatimentActionPerformed

    private void ckbDirecteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbDirecteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbDirecteurActionPerformed

    private void ckbSpecialiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbSpecialiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbSpecialiteActionPerformed

    private void txtMedecinTraitantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedecinTraitantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedecinTraitantActionPerformed

    private void ckbChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbChambreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbChambreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_rechercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_rechercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_rechercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_rechercher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_rechercher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLancerRecherche;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox cbRotation;
    private javax.swing.JComboBox cbSpecialite;
    private javax.swing.JComboBox cbSupInf;
    private javax.swing.JCheckBox ckbAdresse;
    private javax.swing.JCheckBox ckbChambre;
    private javax.swing.JCheckBox ckbDirecteur;
    private javax.swing.JCheckBox ckbHospitalisation;
    private javax.swing.JCheckBox ckbMedecinTraitant;
    private javax.swing.JCheckBox ckbMutuelle;
    private javax.swing.JCheckBox ckbNom;
    private javax.swing.JCheckBox ckbNomBatiment;
    private javax.swing.JCheckBox ckbNomService;
    private javax.swing.JCheckBox ckbPrenom;
    private javax.swing.JCheckBox ckbRotation;
    private javax.swing.JCheckBox ckbSalaire;
    private javax.swing.JCheckBox ckbService;
    private javax.swing.JCheckBox ckbSpecialite;
    private javax.swing.JCheckBox ckbTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRechercher;
    private javax.swing.JRadioButton rdbDocteur;
    private javax.swing.JRadioButton rdbEmploye;
    private javax.swing.JRadioButton rdbInfirmier;
    private javax.swing.JRadioButton rdbMalade;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextArea txtAreaRecherche;
    private javax.swing.JTextField txtMedecinTraitant;
    private javax.swing.JTextField txtMutuelle;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNomBatiment;
    private javax.swing.JTextField txtNomService;
    private javax.swing.JTextField txtNumDirecteur;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtValSalaire;
    // End of variables declaration//GEN-END:variables
}
